package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"

	"github.com/weeb-vip/list-service/graph/generated"
	"github.com/weeb-vip/list-service/graph/model"
)

// FindAPIInfoByName is the resolver for the findApiInfoByName field.
func (r *entityResolver) FindAPIInfoByName(ctx context.Context, name string) (*model.APIInfo, error) {
	panic(fmt.Errorf("not implemented: FindAPIInfoByName - findApiInfoByName"))
}

// FindUserAnimeByID is the resolver for the findUserAnimeByID field.
func (r *entityResolver) FindUserAnimeByID(ctx context.Context, id string) (*model.UserAnime, error) {
	panic(fmt.Errorf("not implemented: FindUserAnimeByID - findUserAnimeByID"))
}

// FindUserListByID is the resolver for the findUserListByID field.
func (r *entityResolver) FindUserListByID(ctx context.Context, id string) (*model.UserList, error) {
	panic(fmt.Errorf("not implemented: FindUserListByID - findUserListByID"))
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
