package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"

	"github.com/weeb-vip/list-service/graph/generated"
	"github.com/weeb-vip/list-service/graph/model"
)

// FindAnimeByID is the resolver for the findAnimeByID field.
func (r *entityResolver) FindAnimeByID(ctx context.Context, id string) (*model.Anime, error) {
	return &model.Anime{
		ID: id,
	}, nil
}

// FindAPIInfoByName is the resolver for the findApiInfoByName field.
func (r *entityResolver) FindAPIInfoByName(ctx context.Context, name string) (*model.APIInfo, error) {
	panic(fmt.Errorf("not implemented: FindAPIInfoByName - findApiInfoByName"))
}

// FindUserAnimeByID is the resolver for the findUserAnimeByID field.
func (r *entityResolver) FindUserAnimeByID(ctx context.Context, id string) (*model.UserAnime, error) {
	panic(fmt.Errorf("not implemented: FindUserAnimeByID - findUserAnimeByID"))
}

// FindUserListByID is the resolver for the findUserListByID field.
func (r *entityResolver) FindUserListByID(ctx context.Context, id string) (*model.UserList, error) {
	panic(fmt.Errorf("not implemented: FindUserListByID - findUserListByID"))
}

// FindUserWorkByID is the resolver for the findUserWorkByID field.
func (r *entityResolver) FindUserWorkByID(ctx context.Context, id string) (*model.UserWork, error) {
	panic(fmt.Errorf("not implemented: FindUserWorkByID - findUserWorkByID"))
}

// FindWorkByID is the resolver for the findWorkByID field.
//
// The key and nothing else, exactly as FindAnimeByID above it. This service
// extends Work; it does not own one. Every field but the id comes from
// anime-api, and userWork is resolved from this id.
func (r *entityResolver) FindWorkByID(ctx context.Context, id string) (*model.Work, error) {
	return &model.Work{
		ID: id,
	}, nil
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
