# GraphQL schema example
#
# https://gqlgen.com/getting-started/

type ListServiceAPI {
    "Version of event golang-template service"
    version: String!
}

type ApiInfo @key(fields: "name") {
    "API Info of the ListServiceAPI"
    golangTemplateAPI: ListServiceAPI! @goField(forceResolver: true)
    "Name of the API"
    name: String!
}

type Query {
    UserLists: [UserList!] @Authenticated
    UserAnimes(input: UserAnimesInput!): UserAnimePaginated @Authenticated
    UserWorks(input: UserWorksInput!): UserWorkPaginated @Authenticated
    WatchedEpisodes(animeID: String!): [WatchedEpisode!]! @Authenticated
    ReadChapters(workID: String!): [ReadChapter!]! @Authenticated
}

type Mutation {
    CreateList(input: UserListInput!): UserList! @Authenticated
    DeleteList(id: ID!): Boolean! @Authenticated
    AddAnime(input: UserAnimeInput!): UserAnime! @Authenticated
    UpdateAnime(input: UserAnimeInput!): UserAnime! @Authenticated
    DeleteAnime(id: ID!): Boolean! @Authenticated
    AddWork(input: UserWorkInput!): UserWork! @Authenticated
    UpdateWork(input: UserWorkInput!): UserWork! @Authenticated
    DeleteWork(id: ID!): Boolean! @Authenticated
    MarkEpisodeWatched(input: MarkEpisodeInput!): WatchedEpisode! @Authenticated
    UnmarkEpisodeWatched(input: MarkEpisodeInput!): Boolean! @Authenticated
    MarkChapterRead(input: MarkChapterInput!): ReadChapter! @Authenticated
    UnmarkChapterRead(input: MarkChapterInput!): Boolean! @Authenticated
}