package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"

	"github.com/weeb-vip/list-service/graph/generated"
	"github.com/weeb-vip/list-service/graph/model"
	"github.com/weeb-vip/list-service/internal/resolvers"
)

// GolangTemplateAPI is the resolver for the GolangTemplateAPI field.
func (r *apiInfoResolver) GolangTemplateAPI(ctx context.Context, obj *model.APIInfo) (*model.ListServiceAPI, error) {
	panic(fmt.Errorf("not implemented: GolangTemplateAPI - GolangTemplateAPI"))
}

// CreateList is the resolver for the CreateList field.
func (r *mutationResolver) CreateList(ctx context.Context, input model.UserListInput) (*model.UserList, error) {
	return resolvers.UpsertUserList(ctx, r.UserListService, input)
}

// DeleteList is the resolver for the DeleteList field.
func (r *mutationResolver) DeleteList(ctx context.Context, id string) (bool, error) {
	err := resolvers.DeleteUserList(ctx, r.UserListService, id)
	if err != nil {
		return false, err
	}
	return true, nil
}

// AddAnime is the resolver for the AddAnime field.
func (r *mutationResolver) AddAnime(ctx context.Context, input model.UserAnimeInput) (*model.UserAnime, error) {
	return resolvers.UpsertUserAnime(ctx, r.UserAnimeService, input)
}

// UpdateAnime is the resolver for the UpdateAnime field.
func (r *mutationResolver) UpdateAnime(ctx context.Context, input model.UserAnimeInput) (*model.UserAnime, error) {
	return resolvers.UpsertUserAnime(ctx, r.UserAnimeService, input)
}

// DeleteAnime is the resolver for the DeleteAnime field.
func (r *mutationResolver) DeleteAnime(ctx context.Context, id string) (bool, error) {
	err := resolvers.DeleteUserAnime(ctx, r.UserAnimeService, id)
	if err != nil {
		return false, err
	}
	return true, nil
}

// AddWork is the resolver for the AddWork field.
func (r *mutationResolver) AddWork(ctx context.Context, input model.UserWorkInput) (*model.UserWork, error) {
	return resolvers.UpsertUserWork(ctx, r.UserWorkService, input)
}

// UpdateWork is the resolver for the UpdateWork field.
func (r *mutationResolver) UpdateWork(ctx context.Context, input model.UserWorkInput) (*model.UserWork, error) {
	// Same resolver as AddWork: the write is keyed on (user, work), so adding
	// something already on the shelf updates it rather than duplicating it.
	return resolvers.UpsertUserWork(ctx, r.UserWorkService, input)
}

// DeleteWork is the resolver for the DeleteWork field.
func (r *mutationResolver) DeleteWork(ctx context.Context, id string) (bool, error) {
	if err := resolvers.DeleteUserWork(ctx, r.UserWorkService, id); err != nil {
		return false, err
	}

	return true, nil
}

// MarkEpisodeWatched is the resolver for the MarkEpisodeWatched field.
func (r *mutationResolver) MarkEpisodeWatched(ctx context.Context, input model.MarkEpisodeInput) (*model.WatchedEpisode, error) {
	return resolvers.MarkEpisodeWatched(ctx, r.UserProgressService, input)
}

// UnmarkEpisodeWatched is the resolver for the UnmarkEpisodeWatched field.
func (r *mutationResolver) UnmarkEpisodeWatched(ctx context.Context, input model.MarkEpisodeInput) (bool, error) {
	if err := resolvers.UnmarkEpisodeWatched(ctx, r.UserProgressService, input); err != nil {
		return false, err
	}

	return true, nil
}

// MarkChapterRead is the resolver for the MarkChapterRead field.
func (r *mutationResolver) MarkChapterRead(ctx context.Context, input model.MarkChapterInput) (*model.ReadChapter, error) {
	return resolvers.MarkChapterRead(ctx, r.UserProgressService, input)
}

// UnmarkChapterRead is the resolver for the UnmarkChapterRead field.
func (r *mutationResolver) UnmarkChapterRead(ctx context.Context, input model.MarkChapterInput) (bool, error) {
	if err := resolvers.UnmarkChapterRead(ctx, r.UserProgressService, input); err != nil {
		return false, err
	}

	return true, nil
}

// UserLists is the resolver for the UserLists field.
func (r *queryResolver) UserLists(ctx context.Context) ([]*model.UserList, error) {
	return resolvers.GetUserListsByID(ctx, r.UserListService)
}

// UserAnimes is the resolver for the UserAnimes field.
func (r *queryResolver) UserAnimes(ctx context.Context, input model.UserAnimesInput) (*model.UserAnimePaginated, error) {
	return resolvers.GetUserAnimesByID(ctx, r.UserAnimeService, input)
}

// UserWorks is the resolver for the UserWorks field.
func (r *queryResolver) UserWorks(ctx context.Context, input model.UserWorksInput) (*model.UserWorkPaginated, error) {
	return resolvers.UserWorks(ctx, r.UserWorkService, input)
}

// UserAnimeStatusCounts is the resolver for the UserAnimeStatusCounts field.
func (r *queryResolver) UserAnimeStatusCounts(ctx context.Context) (*model.UserAnimeStatusCounts, error) {
	return resolvers.UserAnimeStatusCounts(ctx, r.UserAnimeService)
}

// UserWorkStatusCounts is the resolver for the UserWorkStatusCounts field.
func (r *queryResolver) UserWorkStatusCounts(ctx context.Context) (*model.UserWorkStatusCounts, error) {
	return resolvers.UserWorkStatusCounts(ctx, r.UserWorkService)
}

// PublicUserAnimes is the resolver for the PublicUserAnimes field.
func (r *queryResolver) PublicUserAnimes(ctx context.Context, userID string, input model.UserAnimesInput) (*model.UserAnimePaginated, error) {
	return resolvers.PublicUserAnimes(ctx, r.UserAnimeService, userID, input)
}

// PublicUserWorks is the resolver for the PublicUserWorks field.
func (r *queryResolver) PublicUserWorks(ctx context.Context, userID string, input model.UserWorksInput) (*model.UserWorkPaginated, error) {
	return resolvers.PublicUserWorks(ctx, r.UserWorkService, userID, input)
}

// PublicUserAnimeStatusCounts is the resolver for the PublicUserAnimeStatusCounts field.
func (r *queryResolver) PublicUserAnimeStatusCounts(ctx context.Context, userID string) (*model.UserAnimeStatusCounts, error) {
	return resolvers.PublicUserAnimeStatusCounts(ctx, r.UserAnimeService, userID)
}

// PublicUserWorkStatusCounts is the resolver for the PublicUserWorkStatusCounts field.
func (r *queryResolver) PublicUserWorkStatusCounts(ctx context.Context, userID string) (*model.UserWorkStatusCounts, error) {
	return resolvers.PublicUserWorkStatusCounts(ctx, r.UserWorkService, userID)
}

// WatchedEpisodes is the resolver for the WatchedEpisodes field.
func (r *queryResolver) WatchedEpisodes(ctx context.Context, animeID string) ([]*model.WatchedEpisode, error) {
	return resolvers.WatchedEpisodes(ctx, r.UserProgressService, animeID)
}

// ReadChapters is the resolver for the ReadChapters field.
func (r *queryResolver) ReadChapters(ctx context.Context, workID string) ([]*model.ReadChapter, error) {
	return resolvers.ReadChapters(ctx, r.UserProgressService, workID)
}

// ApiInfo returns generated.ApiInfoResolver implementation.
func (r *Resolver) ApiInfo() generated.ApiInfoResolver { return &apiInfoResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type apiInfoResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
