package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"

	"github.com/weeb-vip/golang-template/graph/generated"
	"github.com/weeb-vip/golang-template/graph/model"
)

// GolangTemplateAPI is the resolver for the GolangTemplateAPI field.
func (r *apiInfoResolver) GolangTemplateAPI(ctx context.Context, obj *model.APIInfo) (*model.GolangTemplateAPI, error) {
	panic(fmt.Errorf("not implemented: GolangTemplateAPI - GolangTemplateAPI"))
}

// Hello is the resolver for the Hello field.
func (r *queryResolver) Hello(ctx context.Context) (string, error) {
	panic(fmt.Errorf("not implemented: Hello - Hello"))
}

// ApiInfo returns generated.ApiInfoResolver implementation.
func (r *Resolver) ApiInfo() generated.ApiInfoResolver { return &apiInfoResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type apiInfoResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
