package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"

	"github.com/weeb-vip/list-service/graph/generated"
	"github.com/weeb-vip/list-service/graph/model"
	"github.com/weeb-vip/list-service/internal/resolvers"
)

// UserAnime is the resolver for the userAnime field.
func (r *animeResolver) UserAnime(ctx context.Context, obj *model.Anime) (*model.UserAnime, error) {
	return resolvers.GetUserAnimeByAnimeIDWithLoader(ctx, obj.ID)
}

// UserWork is the resolver for the userWork field.
func (r *workResolver) UserWork(ctx context.Context, obj *model.Work) (*model.UserWork, error) {
	return resolvers.GetUserWorkByWorkIDWithLoader(ctx, obj.ID)
}

// Anime returns generated.AnimeResolver implementation.
func (r *Resolver) Anime() generated.AnimeResolver { return &animeResolver{r} }

// Work returns generated.WorkResolver implementation.
func (r *Resolver) Work() generated.WorkResolver { return &workResolver{r} }

type animeResolver struct{ *Resolver }
type workResolver struct{ *Resolver }
