// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type APIInfo struct {
	// API Info of the golang-tempalte
	GolangTemplateAPI *GolangTemplateAPI `json:"golangTemplateAPI"`
	// Name of the API
	Name string `json:"name"`
}

func (APIInfo) IsEntity() {}

type GolangTemplateAPI struct {
	// Version of event golang-template service
	Version string `json:"version"`
}
