name: Template Rename

on:
  push:
    branches: [main]

jobs:
  rename:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21' # change to match your Go version

      - name: Extract Repo Info
        id: repo
        run: |
          REPO_NAME=$(basename ${{ github.repository }})
          echo "REPO_NAME=$REPO_NAME" >> "$GITHUB_OUTPUT"
          TYPE_NAME=$(echo "$REPO_NAME" | sed -r 's/(^|-)([a-z])/\U\2/g')API
          echo "TYPE_NAME=$TYPE_NAME" >> "$GITHUB_OUTPUT"

      - name: Check for placeholder
        id: check
        run: |
          if grep -r 'list-service' . || grep -r 'golangTemplateAPI' .; then
            echo "found=true" >> "$GITHUB_OUTPUT"
          else
            echo "found=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Replace template strings
        if: steps.check.outputs.found == 'true'
        run: |
          find . -type f \( -name '*.go' -o -name '*.graphql' -o -name '*.gql' -o -name '*.mod' -o -name '*.yml' -o -name '*.yaml' \) \
            -not -path "./.git/*" \
            -exec sed -i "s/list-service/${{ steps.repo.outputs.REPO_NAME }}/g" {} +

          find . -type f \( -name '*.go' -o -name '*.graphql' -o -name '*.gql' \) \
            -not -path "./.git/*" \
            -exec sed -i "s/golangTemplateAPI/${{ steps.repo.outputs.TYPE_NAME }}/g" {} +

          find . -type d -name 'list-service' | while read -r dir; do
            newdir=$(echo "$dir" | sed "s/list-service/${{ steps.repo.outputs.REPO_NAME }}/")
            mv "$dir" "$newdir"
          done

      - name: Tidy Go Modules
        run: go mod tidy

      - name: Run gqlgen generate
        run: go run github.com/99designs/gqlgen generate

      - name: Commit changes
        if: steps.check.outputs.found == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "chore: rename template and generate gql files"
          git push
